<<<<<<< HEAD
# Generated by Django 4.2.21 on 2025-05-17 22:17
=======
# Generated by Django 5.2.1 on 2025-05-17 19:42
>>>>>>> 1842ccfc7c492860779479f2fff6999835207543

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
    ]
